# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active-record-transactioner 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "active-record-transactioner"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2015-12-05"
  s.description = "Queue up calls to specific models and execute them in transactions, after a certain number of models have been added."
  s.email = "kj@gfish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = Dir["{config,lib}/**/*", "Rakefile"]
  s.homepage = "http://github.com/kaspernj/active-record-transactioner"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Queue up calls to specific models and execute them in transactions, after a certain number of models have been added."

  s.add_dependency("rails", ">= 6.0.0")
end
