# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active-record-transactioner 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "active-record-transactioner"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2015-12-05"
  s.description = "Queue up calls to specific models and execute them in transactions, after a certain number of models have been added."
  s.email = "kj@gfish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = Dir["{config,lib}/**/*", "Rakefile"]
  s.homepage = "http://github.com/kaspernj/active-record-transactioner"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Queue up calls to specific models and execute them in transactions, after a certain number of models have been added."

  s.add_dependency("rails", ">= 6.0.0")

  s.add_development_dependency("appraisal")
  s.add_development_dependency("best_practice_project")
  s.add_development_dependency("rspec-rails", "~> 5.1.0")
  s.add_development_dependency("rdoc", "~> 6.2")
  s.add_development_dependency("bundler", [">= 1.0.0"])
  s.add_development_dependency("builder", [">= 0"])
  s.add_development_dependency("activerecord", [">= 0"])
  s.add_development_dependency("sqlite3", "= 1.4.2")
  s.add_development_dependency("mysql2", "= 0.5.4")
  s.add_development_dependency("pry", [">= 0"])
  s.add_development_dependency("rubocop", "= 1.30.0")
  s.add_development_dependency("database_cleaner", [">= 0"])
  s.add_development_dependency("rubocop-performance")
  s.add_development_dependency("rubocop-rails")
  s.add_development_dependency("rubocop-rspec")
  s.add_development_dependency("tzinfo-data")
end
