before_script:
  - wait-for-it mysql:3306
  - cd spec/dummy && cp config/database.peakflow.yml config/database.yml
  - bundle exec appraisal bundle
  - cd spec/dummy && RAILS_ENV=test bundle exec rails db:create db:environment:set db:schema:load
services:
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=active_record_transactioner_test
    image: mysql:5.7.29
    expose:
      - 3306
    restart_policy: on-failure
builds:
  build_1:
    environment:
      RUBY_VERSION: 2.7.8
    name: Ruby 2.7.8, Rails 6
    script:
      - bundle exec appraisal "ruby 2 rails 6" rspec
  build_2:
    environment:
      RUBY_VERSION: 2.7.8
    name: Ruby 2.7.8, Rails 7
    script:
      - bundle exec appraisal "ruby 2 rails 7" rspec
  build_3:
    environment:
      RUBY_VERSION: 3.2.2
    name: Ruby 3.2.2, Rails 6
    script:
      - bundle exec appraisal "ruby 3 rails 6" rspec
  build_4:
    environment:
      RUBY_VERSION: 3.2.2
    name: Ruby 3.2.2, Rails 7
    script:
      - bundle exec appraisal "ruby 3 rails 7" rspec
  build_5:
    name: Linters
    script:
      - bundle exec rake best_practice_project:run
