before_install:
  - sudo apt-get install libmysqlclient-dev
before_script:
  - cd spec/dummy && cp config/database.peakflow.yml config/database.yml
  - cd spec/dummy && RAILS_ENV=test bundle exec rails db:create db:environment:set db:schema:load
rvm: true
services:
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=active_record_transactioner_test
    image: mysql:5.7.29
    expose:
      - 3306
script:
  - bundle exec rspec
  - bundle exec rake best_practice_project:run
