before_script:
  - wait-for-it mysql:3306
  - cd spec/dummy && cp config/database.peakflow.yml config/database.yml
  - cd spec/dummy && RAILS_ENV=test bundle exec rails db:create db:environment:set db:schema:load
rvm: true
services:
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=active_record_transactioner_test
    image: mysql:5.7.29
    expose:
      - 3306
    restart_policy: on-failure
builds:
  build_1:
    name: Ruby 2.7.8, Rails 6
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_2_rails_6.gemfile
      - RUBY_VERSION=2.7.8
    script:
      - bundle exec appraisal "ruby 2 rails 6" rspec
  build_2:
    name: Ruby 2.7.8, Rails 7
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_2_rails_7.gemfile
      - RUBY_VERSION=2.7.8
    script:
      - bundle exec appraisal "ruby 2 rails 7" rspec
  build_3:
    name: Ruby 3.2.2, Rails 6
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_3_rails_6.gemfile
      - RUBY_VERSION=3.2.2
    script:
      - bundle exec appraisal "ruby 3 rails 6" rspec
  build_4:
    name: Ruby 3.2.2, Rails 7
    environment:
      - BUNDLE_GEMFILE=gemfiles/ruby_3_rails_7.gemfile
      - RUBY_VERSION=3.2.2
    script:
      - bundle exec appraisal "ruby 3 rails 7" rspec
  build_5:
    name: Linters
    script:
      - bundle exec rake best_practice_project:run
